# Generated by Django 2.2.3 on 2020-04-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-put_time']},
        ),
    ]
